DeliverNET/Controllers/DashboardBusiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DeliverNET.Controllers
{
    [Authorize(Policy = "OwnerOnly")]
    public class DashboardBusiController : Controller
    {
        // Dummy slave dashboard data
        private static Models.ProfileDummies.BusiDashboardDummyModel Dashboard_Dummy = new Models.ProfileDummies.BusiDashboardDummyModel
        {
            expensesSaved = 132,
            totalIncome = 684,
            totalOrders = 80,
            totalOrdersSucceeded = 77,
            totalHoursWorking = 90,
            totalDaysWorking = 13,
            ordersCounterPerDayActive = new int[] { 2, 5, 3, 10, 4, 3, 6, 5, 2, 15, 14, 6, 5 },
            ordersCounterPerDayType = new List<int> { 24, 10, 8, 6, 7, 7, 18 }
        };

        public IActionResult OverviewBusi()
        {
            return View(Dashboard_Dummy);
        }

        public IActionResult OrdersBusi()
        {
            return View(Dashboard_Dummy);
        }

        public IActionResult ProfitBusi()
        {
            return View(Dashboard_Dummy);
        }
    }
}

DeliverNET/Controllers/DashboardIndiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DeliverNET.Controllers
{
    [Authorize(Policy = "IndividualOnly")]
    public class DashboardIndiController : Controller
    {
        // Dummy slave dashboard data
        private static Models.ProfileDummies.IndiDashboardDummyModel Dashboard_Dummy = new Models.ProfileDummies.IndiDashboardDummyModel
        {
            totalProfit = 1200,
            profitMinusTips = 1100,
            totalOrders = 80,
            totalHoursWorking = 90,
            totalDaysWorking = 13,
            ordersCounterPerDayActive = new int[] { 2, 5, 3, 10, 4, 3, 6, 5, 2, 15, 14, 6, 5 },
            tips = 100,
            ordersCounterPerDayType = new List<int> { 24, 10, 8, 6, 7, 7, 18 }
        };

        public IActionResult OverviewIndi()
        {
            return View(Dashboard_Dummy);
        }

        public IActionResult OrdersIndi()
        {
            return View(Dashboard_Dummy);
        }

        public IActionResult ProfitIndi()
        {
            return View(Dashboard_Dummy);
        }
    }
}

DeliverNET/Views/Shared/_ContactUsPartial.cshtml
@model DeliverNET.Models.HomeViewModels.ContactUsViewModel
<!-- Contact -->
<div class="bg-jet parallax-map">
    <div class="container py-5">
        <div class="row">
            <div class="col">
                <h4 class="text-bone">Contact Us</h4>
            </div>
        </div>
        <div class="row">
            <div class="col">

                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-row">

                        <div class="col">
                            <div class="form-group">
                                <input asp-for="Name" class="form-control" placeholder="Your Name *">
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <input asp-for="Email" class="form-control" placeholder="Your Email *">
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>

                            <div class="form-group mb-0">
                                <input asp-for="PhoneNumber" class="form-control" placeholder="Your Phone *">
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col">
                            <div class="form-group h-100">
                                <textarea asp-for="Message" class="form-control h-100" placeholder="Your Message *"></textarea>
                                <span asp-validation-for="Message" class="text-danger"></span>
                            </div>
                        </div>

                    </div>

                    <div class="form-row mt-3">
                        <div class="col">
                            <div class="form-group">
                                <button asp-controller="Home" asp-action="ContactUs" type="submit" class="btn btn-border-bone text-jet">Send Message</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

        </div>

    </div>
</div>

DeliverNET/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "DeliverNET | Delivery Source";
}
@inject SignInManager<DeliverNETUser> SignInManager
@inject UserManager<DeliverNETUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=PT+Serif:700" rel="stylesheet">

        <link href="~/css/site.css" rel="stylesheet">
        <link href="~/css/OwnCSS.css" rel="stylesheet">
        <link href="~/css/colors.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.min.css"
              asp-fallback-href="~/vendor/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/agency.min.css" asp-append-version="true" />
    </environment>
</head>



<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg sticky-top bg-jet">
        <div class="container">
            <a class="navbar-brand font-pacifico" asp-controller="Home" asp-action="Index">Delivernet</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars text-bone"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>


    <!-- Main Content -->
    <div class="bg-img-burger" id="bodyDiv">
        @RenderBody()
    </div>

    <!-- Footer -->
    <footer class="bg-jet text-bone" id="footer">
        <div class="container py-3">
            <div class="row">
                <div class="col-sm-6 text-left">
                    <span class="copyright">Copyright &copy; Delivernet</span>
                </div>
                <div class="col-sm-6 text-right">
                    <a class="mx-3" href="#">
                        <i class="fab fa-twitter text-bone"></i>
                    </a>
                    <a class="mx-3" href="#">
                        <i class="fab fa-facebook-f text-bone"></i>
                    </a>
                    <a class="mx-3" href="#">
                        <i class="fab fa-linkedin-in text-bone"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>




    <environment include="Development">

        <!-- jQuery -->
        <script src="~/vendor/jquery/jquery.min.js"></script>

        <!-- Bootstrap core JavaScript -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <!-- Signalr JavaScript-->
        <script src="~/lib/signalr/dist/browser/signalr.js"></script>

        <!-- Plugin JavaScript -->
        <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

        <!--Client side validation libraries-->
        <script src="~/vendor/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/vendor/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

        <!--google maps api scripts-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script defer src="https://maps.googleapis.com/maps/api/js?libraries=places&language=en&key=AIzaSyBsxQgSj5tMe7y7LX6P42cTuKlN37aK2Ec" type="text/javascript"></script>


    </environment>
    <environment exclude="Development">
        <script src="~/vendor/jquery/jquery.min.js"
                asp-fallback-src="~/vendor/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>


    @RenderSection("Scripts", required: false)

</body>
</html>

DeliverNET/Views/Shared/_LayoutBusi.cshtml
@{
    ViewData["Title"] = "DeliverNET | Delivery Source";
}
@inject SignInManager<DeliverNETUser> SignInManager
@inject UserManager<DeliverNETUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <environment include="Development">
        <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=PT+Serif:700" rel="stylesheet">
        <link href="~/css/site.css" rel="stylesheet">
        <link href="~/css/OwnCSS.css" rel="stylesheet">
        <link href="~/css/colors.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.min.css"
              asp-fallback-href="~/vendor/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/agency.min.css" asp-append-version="true" />
    </environment>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg sticky-top bg-jet">
        <div class="container">
            <a class="navbar-brand font-pacifico" asp-controller="Home" asp-action="Index">Delivernet</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars text-bone"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <!-- Main Content -->
    <div class="bg-img-winter" id="bodyDiv">
        @RenderBody()
    </div>
    <!-- Footer -->
    <footer class="bg-jet text-bone" id="footer">
        <div class="container py-3">
            <div class="row">
                <div class="col-sm-6 text-left">
                    <span class="copyright">Copyright &copy; Delivernet</span>
                </div>
                <div class="col-sm-6 text-right">
                    <a class="mx-3" href="#">
                        <i class="fab fa-twitter text-bone"></i>
                    </a>
                    <a class="mx-3" href="#">
                        <i class="fab fa-facebook-f text-bone"></i>
                    </a>
                    <a class="mx-3" href="#">
                        <i class="fab fa-linkedin-in text-bone"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>


    <environment include="Development">
        <!-- jQuery -->
        <script src="~/vendor/jquery/jquery.js"></script>

        <!-- Bootstrap core JavaScript -->
        <script src="~/vendor/bootstrap/js/bootstrap.js"></script>

        <!-- Signalr JavaScript-->
        <script src="~/lib/signalr/dist/browser/signalr.js"></script>

        <!-- Plugin JavaScript -->
        <script src="~/vendor/jquery-easing/jquery.easing.js"></script>

        <!--Client side validation libraries-->
        <script src="~/vendor/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/vendor/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

        <!--google maps api scripts-->
        <script defer src="https://maps.googleapis.com/maps/api/js?libraries=places&language=en&key=AIzaSyBsxQgSj5tMe7y7LX6P42cTuKlN37aK2Ec" type="text/javascript"></script>

    </environment>
    <environment exclude="Development">
        <script src="~/vendor/jquery/jquery.min.js"
                asp-fallback-src="~/vendor/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

DeliverNET/Views/Shared/_LayoutDashboard.cshtml
@{
    ViewData["Title"] = "DeliverNET | Dashboard";
}
@inject SignInManager<DeliverNETUser> SignInManager
@inject UserManager<DeliverNETUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <environment include="Development">
        <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=PT+Serif:700" rel="stylesheet">
        <link href="~/css/site.css" rel="stylesheet">
        <link href="~/css/OwnCSS.css" rel="stylesheet">
        <link href="~/css/colors.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.min.css"
              asp-fallback-href="~/vendor/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/agency.min.css" asp-append-version="true" />
    </environment>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg sticky-top bg-jet">
        <div class="container">
            <a class="navbar-brand font-pacifico" asp-controller="Home" asp-action="Index">Delivernet</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars text-bone"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="bg-dashboard" id="bodyDiv">
        <div class="p-0 m-0">
            <div class="row">
                <div class="container col-md-2 bg-jet m-0 pl-4 pr-2 mh-100" style="max-width:170px">

                    <!-- We DO want it to have a fixed width, don't freak out
                    "Shut up and sit down you big bald fuck"  // google it -->
                    <div class="d-flex flex-column justify-content-start" style="font-size:medium">

                        <div></div>

                        <div class="pt-4" style="color:#808080">Dashboards</div>


                        @if (User.HasClaim(c => c.Value == "Individual"))
                        {

                            <a asp-controller="DashboardIndi" asp-action="OverviewIndi" class="btn bg-jet jet-hov btn-shadow-none text-bone mt-3 pl-1 text-left" style="border-radius:4px" id="btnOverview">
                                <i class="fas fa-map-marker-alt"></i>
                                &ensp;Overview
                            </a>

                            <a asp-controller="DashboardIndi" asp-action="OrdersIndi" class="btn bg-jet jet-hov btn-shadow-none text-bone my-1 pl-1 text-left" style="border-radius:4px" id="btnOrders">
                                <i class="fas fa-road"></i>
                                &ensp;Orders
                            </a>

                            <a asp-controller="DashboardIndi" asp-action="ProfitIndi" class="btn bg-jet jet-hov btn-shadow-none text-bone my-1 pl-1 text-left" style="border-radius:4px" id="btnProfit">
                                <i class="fas fa-dollar-sign"></i>
                                &ensp;Profit
                            </a>
                        }
                        else
                        {
                            <a asp-controller="DashboardBusi" asp-action="OverviewBusi" class="btn bg-jet jet-hov btn-shadow-none text-bone mt-3 pl-1 text-left" style="border-radius:4px" id="btnOverview">
                                <i class="fas fa-map-marker-alt"></i>
                                &ensp;Overview
                            </a>

                            <a asp-controller="DashboardBusi" asp-action="OrdersBusi" class="btn bg-jet jet-hov btn-shadow-none text-bone my-1 pl-1 text-left" style="border-radius:4px" id="btnOrders">
                                <i class="fas fa-road"></i>
                                &ensp;Orders
                            </a>

                            <a asp-controller="DashboardBusi" asp-action="ProfitBusi" class="btn bg-jet jet-hov btn-shadow-none text-bone my-1 pl-1 text-left" style="border-radius:4px" id="btnProfit">
                                <i class="fas fa-dollar-sign"></i>
                                &ensp;Profit
                            </a>
                        }

                    </div>

                </div>

                <div class="col-md-10" id="partialDiv">
                    @RenderBody()
                </div>

            </div>

        </div>
    </div>

    <!-- Footer -->
    <footer class="bg-jet text-bone" id="footer">
        <div class="container py-3">
            <div class="row">
                <div class="col-sm-6 text-left">
                    <span class="copyright">Copyright &copy; Delivernet</span>
                </div>
                <div class="col-sm-6 text-right">
                    <a class="mx-3" href="#">
                        <i class="fab fa-twitter text-bone"></i>
                    </a>
                    <a class="mx-3" href="#">
                        <i class="fab fa-facebook-f text-bone"></i>
                    </a>
                    <a class="mx-3" href="#">
                        <i class="fab fa-linkedin-in text-bone"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>


    <environment include="Development">
        <!-- jQuery -->
        <script src="~/vendor/jquery/jquery.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script src="~/vendor/bootstrap/js/bootstrap.js"></script>
        <!-- Signalr JavaScript-->
        <script src="~/lib/signalr/dist/browser/signalr.js"></script>
        <!-- Plugin JavaScript -->
        <script src="~/vendor/jquery-easing/jquery.easing.js"></script>
        <!-- Client side validation libraries -->
        <script src="~/vendor/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/vendor/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <!-- Google maps api script -->
        <script defer src="https://maps.googleapis.com/maps/api/js?libraries=places&language=en&key=AIzaSyBsxQgSj5tMe7y7LX6P42cTuKlN37aK2Ec" type="text/javascript"></script>

        <!-- Charts -->
        <script src="~/js/Chart.js"></script>
        <script src="~/js/moment/moment.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="~/vendor/jquery/jquery.min.js"
                asp-fallback-src="~/vendor/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"></script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

DeliverNET/Views/Shared/_LayoutIndi.cshtml
@{
    ViewData["Title"] = "DeliverNET | Delivery Source";
}
@inject SignInManager<DeliverNETUser> SignInManager
@inject UserManager<DeliverNETUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <environment include="Development">
        <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=PT+Serif:700" rel="stylesheet">
        <link href="~/css/site.css" rel="stylesheet">
        <link href="~/css/OwnCSS.css" rel="stylesheet">
        <link href="~/css/colors.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.min.css"
              asp-fallback-href="~/vendor/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/agency.min.css" asp-append-version="true" />
    </environment>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg sticky-top bg-jet">
        <div class="container">
            <a class="navbar-brand font-pacifico" asp-controller="Home" asp-action="Index">Delivernet</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars text-bone"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <!-- Main Content -->
    <div class="bg-img-carmine" id="bodyDiv">
        @RenderBody()
    </div>
    <!-- Footer -->
    <footer class="bg-jet text-bone" id="footer">
        <div class="container py-3">
            <div class="row">
                <div class="col-sm-6 text-left">
                    <span class="copyright">Copyright &copy; Delivernet</span>
                </div>
                <div class="col-sm-6 text-right">
                    <a class="mx-3" href="#">
                        <i class="fab fa-twitter text-bone"></i>
                    </a>
                    <a class="mx-3" href="#">
                        <i class="fab fa-facebook-f text-bone"></i>
                    </a>
                    <a class="mx-3" href="#">
                        <i class="fab fa-linkedin-in text-bone"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>


    <environment include="Development">
        <!-- jQuery -->
        <script src="~/vendor/jquery/jquery.js"></script>

        <!-- Bootstrap core JavaScript -->
        <script src="~/vendor/bootstrap/js/bootstrap.js"></script>

        <!-- Signalr JavaScript-->
        <script src="~/lib/signalr/dist/browser/signalr.js"></script>

        <!-- Plugin JavaScript -->
        <script src="~/vendor/jquery-easing/jquery.easing.js"></script>
        
        <!--Client side validation libraries-->
        <script src="~/vendor/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/vendor/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

        <!--google maps api scripts-->
        <script defer src="https://maps.googleapis.com/maps/api/js?libraries=places&language=en&key=AIzaSyBsxQgSj5tMe7y7LX6P42cTuKlN37aK2Ec" type="text/javascript"></script>

    </environment>
    <environment exclude="Development">
        <script src="~/vendor/jquery/jquery.min.js"
                asp-fallback-src="~/vendor/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>