DeliverNET/Models/ProfileIndiViewModels/VerifyFormIndiViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DeliverNET.Models.ProfileIndiViewModels
{
    public class VerifyFormIndiViewModel
    {
        [Required]
        public OperationalCities OperationalCity { get; set; }

        [Required]
        public OperationRegions OperationalRegion { get; set; }

        [Required]
        public string Credentials { get; set; }
    }

    public enum OperationalCities
    {
        [Display(Name ="Αθήνα")]
        Athens
    }

    public enum OperationRegions
    {
        [Display(Name ="Ιλίσια")]
        Ilisia,
        [Display(Name ="Γουδή")]
        Goudi,
        [Display(Name ="Ζωγράφος")]
        Zografos
    }
}

DeliverNET/Controllers/ProfileIndiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeliverNET.Data;
using DeliverNET.Managers.Interfaces;
using DeliverNET.Models;
using DeliverNET.Models.ProfileIndiViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DeliverNET.Controllers
{
    [Authorize(Policy = "IndividualOnly")]
    public class ProfileIndiController : Controller
    {
        // Dummy order data
        private static Models.ProfileDummies.IndiIndixDummyModel Order_Dummy = new Models.ProfileDummies.IndiIndixDummyModel
        {
            IsWorking = false,
            IsVerified = false,
            Username = "Pantazakos",
            ActiveOrders = 3,
            RestaurantName = "Ravaisis",
            RestaurantAddress = "Arxiloxou 0",
            OrderID = 1234,
            FirstName = "Dimosthenis",
            LastName = "Pasparakis",
            Address = "Kapou 32",
            FloorNo = 2,
            DoorName = "AFDEmp",
            PaymentTypeId = 0,
            State = "Picked",
            DistanceToShop = 1.5F,
            ETA = 7,
            Price = 10.4F,
            Stopwatch = 4.03F
        };


        private IDelivererManager _delivererManager;
        private UserManager<DeliverNETUser> _userManager;

        public ProfileIndiController(
            UserManager<DeliverNETUser> userManager,
            IDelivererManager delivererManager
            )
        {
            _delivererManager = delivererManager;
            _userManager = userManager;
        }


        [HttpGet]
        public IActionResult IndexIndi()
        {
            return View(Order_Dummy);
        }

        [HttpGet]
        public IActionResult DashboardIndi()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SettingsIndi()
        {
            return View(Order_Dummy);
        }

        [HttpGet]
        public IActionResult VerifyFormIndi()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VerifyFormIndi(VerifyFormIndiViewModel model)
        {
            if (ModelState.IsValid)
            {
                DeliverNETUser user =  await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
                _delivererManager.SetOperatingRegion(user.Id, $"{model.OperationalCity} / {model.OperationalRegion}");
                _delivererManager.SetCredentials(user.Id, model.Credentials);
                return RedirectToAction("IndexIndi");
            }
            return View(model);
        }
    }
}

DeliverNET/Views/ProfileIndi/IndexIndi.cshtml
@{
    ViewData["Title"] = "DeliverNET | WorkSpace";
    Layout = "~/Views/Shared/_LayoutIndi.cshtml";
}

<!-- Order Info Modal -->
<div class="modal fade rounded" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body bg-jet p-0" style="border-radius: 5px">
                <div class="card text-center">
                    <div class="card-header bg-jet text-bone">
                        <h2 id="modal-restaurantTitle" class="font-pacifico"></h2>
                        <span id="modal-restaurantAddress" class=""></span>
                    </div>
                    <div class="card-body bg-carmine">

                        <p class="">
                            <strong>Payment Type: </strong>
                            <span id="modal-paymentType"></span>
                        </p>

                        <p class="">
                            <strong>Price: </strong>
                            <span id="modal-price"></span>
                        </p>
                                              
                        <input class="form-control" hidden type="text" id="modal-orderId"/>
                        <a onclick="onOrderAccepted()" id="acceptOrderBtn" class="btn bg-winter text-bone d-block">Accept</a>
                    </div>
                    <div id="modal-timestamp" class="card-footer" bg-jet text-bone"></div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Order Accepted Modal -->
<div class="modal fade rounded" id="orderAcceptedModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-jet">
                <h4 class="text-bone">Order Accepted!</h4>
            </div>
            <div class="modal-body bg-bone">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <h5 class="text-jet">Restaurant Info</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Name</span>
                        </div>
                        <div class="col-6">
                            <span id="modalAccepted-restaurantName" class="text-jet">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet mb-0">Address</span>
                        </div>
                        <div class="col-6">
                            <span id="modalAccepted-restaurantAddress" class="text-jet mb-0">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <hr />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <h5 class="text-jet">Order Info</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Price</span>
                        </div>
                        <div class="col-6">
                            <span id="modalAccepted-orderPrice" class="text-jet">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Payment</span>
                        </div>
                        <div class="col-6">
                            <span id="modalAccepted-orderPaymentType" class="text-jet">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button onclick="onOrderPicked()" class="btn btn-block bg-winter text-bone mt-3">Picked Up</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-center bg-jet">
                <input hidden type="text" id="modalAccepted-orderId" />
                <span id="modalAccepted-timestamp" class="text-bone">eliybrliergbly</span>
            </div>
        </div>
    </div>
</div>


<!-- Order Picked Modal -->
<div class="modal fade rounded" id="orderPickedModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-jet">
                <h4 class="text-bone">Order Picked!</h4>
            </div>
            <div class="modal-body bg-bone">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <h5 class="text-jet">Customer Info</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Name</span>
                        </div>
                        <div class="col-6">
                            <span id="modalPicked-customerName" class="text-jet">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Address</span>
                        </div>
                        <div class="col-6">
                            <span id="modalPicked-customerAddress" class="text-jet">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Door Name</span>
                        </div>
                        <div class="col-6">
                            <span id="modalPicked-customerDoorName" class="text-jet">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Floor No</span>
                        </div>
                        <div class="col-6">
                            <span id="modalPicked-customerFloorNo" class="text-jet">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Phone Number</span>
                        </div>
                        <div class="col-6">
                            <span id="modalPicked-customerPhoneNumber" class="text-jet">tade</span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <hr />
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <h5 class="text-jet">Order Info</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Price</span>
                        </div>
                        <div class="col-6">
                            <span id="modalPicked-orderPrice" class="text-jet">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-jet">Payment</span>
                        </div>
                        <div class="col-6">
                            <span id="modalPicked-orderPaymentType" class="text-jet">tade</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button onclick="onOrderDelivered()" class="btn btn-block bg-winter text-bone mt-3">Delivered</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-center bg-jet">
                <input hidden type="text" id="modalPicked-orderId" />
                <span id="modalAccepted-timestamp" class="text-bone">eliybrliergbly</span>
            </div>
        </div>
    </div>
</div>


<div class="container pt-5">
    <div class="row">

        <!-- Order List for Deliverer -->
        <div class="col-md-6 px-0 bg-carmine-3d" onclick="event.stopPropagation()" style="border:solid 1px #E0DDC3;border-radius:4px;height:70vh">
            <div id="orderList" class="list-group">
                <div class="list-group-item flex-column align-items-center bg-jet">
                    <span class="text-bone">Order Pool</span>
                </div>
                <!--Orders go here-->
            </div>
        </div>
        <!-- TODO : Enter Tips button -->


        <!-- Availability Button -->
        <div class="col-md-6" style="text-align:-webkit-center">
            <!-- Ignore error here, all good -->
            <button class="btn btn-unavailable btn-shadow-none text-bone" id="btnReady">
                <i class="fas fa-signal" style="font-size: 70px"></i>
                <p>Not Available</p>
            </button>
        </div>

    </div>

    <!--Test button to remove order based on id-->
    <div class="row no-gutters mt-3">
        <div class="col-md-5">
            <input type="text" id="orderToRemove" class="form-control" placeholder="Order Id" />
        </div>
        <div class="col-md-1">
            <button type="button" id="removeOrderBtn" class="btn btn-danger">Delete</button>
        </div>
    </div>

</div>


@section Scripts {

    <!-- Background Image -->
    <script>
        var back = document.getElementById('bodyDiv');
        back.classList.remove("bg-img-carmine");
        back.classList.add("bg-img-biker");
    </script>

    <!-- Available Button Logic -->
    <script>



            var userName = "@User.Identity.Name";
            var IsClicked = false;
            var btn = document.getElementById('btnReady');
            var IsWorking = document.getElementById('IsWorking');
            var htmlON = '<i class="fas fa-signal" style="font-size: 70px"></i> <p> Not Available</p >';
            var htmlOFF = '<i class="fas fa-check" style="font-size: 70px"></i> <p> Available</p >';


        btn.onclick = function () {
            IsClicked ?
                (IsClicked = false,
                    btn.classList.add("btn-unavailable"),
                    btn.classList.remove("btn-available"),
                    btn.innerHTML = htmlON,
                    removeMeFromGroup(), // Remove from group of available deliverers
                    clearOrderList()) :   

                    (IsClicked = true,
                        btn.classList.add("btn-available"),
                        btn.classList.remove("btn-unavailable"),
                        btn.innerHTML = htmlOFF,
                        addMeToGroup());         // Add to group  -- bugs everything fuck off gamw tin panagia
            }

    </script>

    <script src="~/js/IndiClientSide.js"></script>


}

DeliverNET/Views/ProfileIndi/ReviewsIndi.cshtml

@{
    ViewData["Title"] = "Reviews";
    Layout = "~/Views/Shared/_LayoutIndi.cshtml";
}

<h2>ReviewsIndi</h2>


DeliverNET/Views/ProfileIndi/SettingsIndi.cshtml
@model DeliverNET.Models.ProfileDummies.IndiIndixDummyModel

@{
    ViewData["Title"] = "Profile Settings";
    Layout = "~/Views/Shared/_LayoutIndi.cshtml";
}

<div class="container p-4">

    <div class="row">

        <!-- Options -->
        <div class="col-md-6">

            <div class="d-flex flex-column justify-content-around" style="height:100vh">

                <!-- Profile Settings btn -->
                <a class="d-flex align-items-center justify-content-start" id="btnSett">

                    <div class="btn bg-jet-3d circle text-bone align-items-center d-flex" id="circleSett">
                        <i class="fas fa-user-edit m-auto" style="font-size: 33px"></i>
                    </div>

                    <div class="btn col-md-5 bg-jet-3d text-bone py-1"
                         style="border-radius:20px;font-size:25px;" id="labSett">
                        Profile Settings
                    </div>

                </a>

                <!-- Edit Information btn -->
                <a class="d-flex align-items-center justify-content-start" id="btnInfo">

                    <div class="btn bg-jet-3d circle text-bone align-items-center d-flex" id="circleInfo">
                        <i class="fas fa-unlock-alt m-auto" style="font-size: 33px"></i>
                    </div>

                    <div class="btn col-md-5 bg-jet-3d text-bone py-1"
                         style="border-radius:20px;font-size:25px;" id="labInfo">
                        Edit Info
                    </div>

                </a>

                <!-- Help btn -->
                <a class="d-flex align-items-center justify-content-start" id="btnHelp">

                    <div class="btn bg-jet-3d circle text-bone align-items-center d-flex" id="circleHelp">
                        <i class="fas fa-question m-auto" style="font-size: 33px"></i>
                    </div>

                    <div class="btn col-md-5 bg-jet-3d text-bone py-1"
                         style="border-radius:20px;font-size:25px;" id="labHelp">
                        Help
                    </div>

                </a>

                <!-- Verify btn -->
                @if (!Model.IsVerified)
                {
                    <a class="d-flex align-items-center justify-content-start" id="btnVerify">

                        <div class="btn bg-jet-green-3d circle text-bone align-items-center d-flex" style="text-align:center" id="circleVerify">
                            <i class="fas fa-address-card m-auto" style="font-size: 33px"></i>
                        </div>

                        <div class="btn col-md-5 bg-jet-green-3d text-bone py-1"
                             style="border-radius:20px;font-size:25px;" id="labVerify">
                            Verify
                        </div>
                    </a>
                }
                else
                {
                    <div></div>
                }

                <div></div>
                <div></div>



            </div>

        </div>

        <!-- Menus -->
        <partial name="_SettingsIndiPartial" />

    </div>
</div>



@section Scripts {

    <script>

        var settClicked = false;
        var infoClicked = false;
        var cashClicked = false;
        var helpClicked = false;
        var verifyClicked = false;

        var sett = document.getElementById('btnSett');
        var info = document.getElementById('btnInfo');
        var cash = document.getElementById('btnCashier');
        var help = document.getElementById('btnHelp');
        var verify = document.getElementById('btnVerify');

        var settCircle = document.getElementById('circleSett');
        var infoCircle = document.getElementById('circleInfo');
        var cashCircle = document.getElementById('circleCashier');
        var helpCircle = document.getElementById('circleHelp');
        var verifyCircle = document.getElementById('circleVerify');

        var settLab = document.getElementById('labSett');
        var infoLab = document.getElementById('labInfo');
        var cashLab = document.getElementById('labCashier');
        var helpLab = document.getElementById('labHelp');
        var verifyLab = document.getElementById('labVerify');

        var settMenu = document.getElementById('menuSett');
        var infoMenu = document.getElementById('menuInfo');
        var cashMenu = document.getElementById('menuCashier');
        var helpMenu = document.getElementById('menuHelp');
        var verifyMenu = document.getElementById('menuVerify');


        sett.onmouseover = function () {
            settLab.classList.add("bg-jet-3d-hov");
            settCircle.classList.add("bg-jet-3d-hov");
        };

        sett.onmouseout = function () {
            settLab.classList.remove("bg-jet-3d-hov");
            settCircle.classList.remove("bg-jet-3d-hov");
        };

        info.onmouseover = function () {
            infoLab.classList.add("bg-jet-3d-hov");
            infoCircle.classList.add("bg-jet-3d-hov");
        };

        info.onmouseout = function () {
            infoLab.classList.remove("bg-jet-3d-hov");
            infoCircle.classList.remove("bg-jet-3d-hov");
        };

        help.onmouseover = function () {
            helpLab.classList.add("bg-jet-3d-hov");
            helpCircle.classList.add("bg-jet-3d-hov");
        };

        help.onmouseout = function () {
            helpLab.classList.remove("bg-jet-3d-hov");
            helpCircle.classList.remove("bg-jet-3d-hov");
        };

        function disableAll() {

            if (settClicked) {
                settCircle.classList.remove("regiClicked"),
                    settLab.classList.remove("regiClicked"),
                    settMenu.classList.add("invisible"),
                    settClicked = false
            };
            if (infoClicked) {
                infoCircle.classList.remove("regiClicked"),
                    infoLab.classList.remove("regiClicked"),
                    infoMenu.classList.add("invisible"),
                    infoClicked = false
            };
            if (cashClicked) {
                cashCircle.classList.remove("regiClicked"),
                    cashLab.classList.remove("regiClicked"),
                    cashMenu.classList.add("invisible"),
                    cashClicked = false
            };
            if (helpClicked) {
                helpCircle.classList.remove("regiClicked"),
                    helpLab.classList.remove("regiClicked"),
                    helpMenu.classList.add("invisible"),
                    helpClicked = false
            };
            if (verifyClicked) {
                verifyCircle.classList.remove("regiClicked"),
                    verifyLab.classList.remove("regiClicked"),
                    verifyMenu.classList.add("invisible"),
                    verifyClicked = false
            };
        };

        sett.onclick = function () {
            settClicked ? disableAll() :
                (disableAll(),
                    settCircle.classList.add("regiClicked"),
                    settLab.classList.add("regiClicked"),
                    settMenu.classList.remove("invisible"),
                    settClicked = true);
        };

        info.onclick = function () {
            infoClicked ? disableAll() :
                (disableAll(),
                    infoCircle.classList.add("regiClicked"),
                    infoLab.classList.add("regiClicked"),
                    infoMenu.classList.remove("invisible"),
                    infoClicked = true);
        };

        help.onclick = function () {
            helpClicked ? disableAll() :
                (disableAll(),
                    helpCircle.classList.add("regiClicked"),
                    helpLab.classList.add("regiClicked"),
                    helpMenu.classList.remove("invisible"),
                    helpClicked = true);
        };

    </script>

    @if (!Model.IsVerified)
    {
        <script>

            var verifyClicked = false;
            var verify = document.getElementById('btnVerify');
            var verifyCircle = document.getElementById('circleVerify');
            var verifyLab = document.getElementById('labVerify');
            var verifyMenu = document.getElementById('menuVerify');

            verify.onmouseover = function () {
                verifyLab.classList.add("bg-jet-green-3d-hov");
                verifyCircle.classList.add("bg-jet-green-3d-hov");
            };

            verify.onmouseout = function () {
                verifyLab.classList.remove("bg-jet-green-3d-hov");
                verifyCircle.classList.remove("bg-jet-green-3d-hov");
            };

            if (verifyClicked) {
                verifyCircle.classList.remove("regiClicked"),
                    verifyLab.classList.remove("regiClicked"),
                    verifyMenu.classList.add("invisible"),
                    verifyClicked = false
            };

            verify.onclick = function () {
                verifyClicked ? disableAll() :
                    (disableAll(),
                        verifyCircle.classList.add("regiClicked"),
                        verifyLab.classList.add("regiClicked"),
                        verifyMenu.classList.remove("invisible"),
                        verifyClicked = true);
            };



        </script>
    }
}

DeliverNET/Views/ProfileIndi/VerifyFormIndi.cshtml
@model DeliverNET.Models.ProfileIndiViewModels.VerifyFormIndiViewModel
@using DeliverNET.Models.ProfileIndiViewModels

@{
    ViewData["Title"] = "Verify Account";
    Layout = "~/Views/Shared/_LayoutIndi.cshtml";
}

<div class="row nav-padding px-5 pb-5">
    <div class="container align-items-center">
        <div class="row align-items-center">
            <div class="col-md-4">
                <h3>Verification Form</h3>
                <br />
                <!-- TODO :: Connect the inputs of this form with Db -->
                <form class="text-my-dark" method="post">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label asp-for="OperationalCity">City</label>
                        <select asp-for="OperationalCity" asp-items="Html.GetEnumSelectList<OperationalCities>()" class="form-control"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="OperationalRegion">Region</label>
                        <select asp-for="OperationalRegion" asp-items="Html.GetEnumSelectList<OperationRegions>()" class="form-control"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Credentials"></label>
                        <input asp-for="Credentials" type="text" class="form-control"/>
                        <span asp-validation-for="Credentials" class="text-danger"></span>
                    </div>

                    <button asp-controller="ProfileIndi" asp-action="VerifyFormIndi" type="submit" class="btn btn-my-dark">Apply</button>
                </form>
            </div>

        </div>

    </div>
</div>>